// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ6oXduZB42g6yWt4IeJBMRLAuaoug6uM',
    appId: '1:104927476063:web:af2df85e1e5efc44a85eea',
    messagingSenderId: '104927476063',
    projectId: 'mom-pulse',
    authDomain: 'mom-pulse.firebaseapp.com',
    storageBucket: 'mom-pulse.firebasestorage.app',
    measurementId: 'G-2D303FLSF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb3NViQK0XAVX_XEBIs7akPGsI5Y_Hc64',
    appId: '1:104927476063:android:fb9d8bda7626e589a85eea',
    messagingSenderId: '104927476063',
    projectId: 'mom-pulse',
    storageBucket: 'mom-pulse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxlyHraUx0ZUIGnmjjh2B3BNBWSI-QzMo',
    appId: '1:104927476063:ios:186ef884ed759172a85eea',
    messagingSenderId: '104927476063',
    projectId: 'mom-pulse',
    storageBucket: 'mom-pulse.firebasestorage.app',
    iosBundleId: 'com.example.momPulseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxlyHraUx0ZUIGnmjjh2B3BNBWSI-QzMo',
    appId: '1:104927476063:ios:186ef884ed759172a85eea',
    messagingSenderId: '104927476063',
    projectId: 'mom-pulse',
    storageBucket: 'mom-pulse.firebasestorage.app',
    iosBundleId: 'com.example.momPulseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ6oXduZB42g6yWt4IeJBMRLAuaoug6uM',
    appId: '1:104927476063:web:b6905c2a6250e10da85eea',
    messagingSenderId: '104927476063',
    projectId: 'mom-pulse',
    authDomain: 'mom-pulse.firebaseapp.com',
    storageBucket: 'mom-pulse.firebasestorage.app',
    measurementId: 'G-6K2JBFX6VV',
  );
}
